#include "dslink/launch.hpp"

namespace dslink {

std::string cfgQuote(const std::string& v) {
    std::string o = "\"";
    for (char c : v)
        if (c != '"' && c != '\n' && c != '\r' && c != '\0') o += c;
    return o + "\"";
}

namespace {
void kv(std::string& s, const char* k, const std::string& v) { s += std::string(k) + " = " + cfgQuote(v) + "\n"; }
void kvb(std::string& s, const char* k, bool v) { kv(s, k, v ? "true" : "false"); }
}  // namespace

std::string buildRetroArchConfig(const LaunchPlan& p) {
    std::string s = "# Generated by DSLink. Do not edit; it is rewritten at every launch.\n";
    kv(s, "libretro_directory", p.corePath.empty() ? "" : p.corePath.substr(0, p.corePath.find_last_of('/') == std::string::npos ? 0 : p.corePath.find_last_of('/')));
    kv(s, "system_directory", p.systemDir);
    kv(s, "savefile_directory", p.saveDir);
    kv(s, "savestate_directory", p.stateDir);
    // Use ONE options file that DSLink rewrites at every launch: RetroArch only seeds a per-core file once, which
    // would freeze the boot mode / screen layout of the first session.
    kv(s, "core_options_path", p.configDir + "/melondsds.opt");
    kvb(s, "global_core_options", true);
    kvb(s, "game_specific_options", false);
    if (!p.infoDir.empty()) kv(s, "libretro_info_path", p.infoDir);
    // Identity: the core derives the emulated DS MAC from this nickname.
    kv(s, "netplay_nickname", p.identity.netplayNick());
    // LAN only: no relay, no UPnP, no public lobby, no spectators.
    kvb(s, "netplay_use_mitm_server", false);
    kvb(s, "netplay_nat_traversal", false);
    kvb(s, "netplay_public_announce", false);
    kvb(s, "netplay_start_as_spectator", false);
    kv(s, "netplay_ip_port", std::to_string(p.port));
    if (p.role == Role::Client) kv(s, "netplay_ip_address", p.hostIp);
    kv(s, "netplay_max_connections", std::to_string(p.maxPlayers > 1 ? p.maxPlayers - 1 : 1));
    // Reliability: flush SRAM often so that suspending / killing the app cannot lose or corrupt the save.
    kv(s, "autosave_interval", "10");
    kvb(s, "config_save_on_exit", false);
    kvb(s, "savestate_auto_save", false);
    kvb(s, "savestate_auto_load", false);
    kvb(s, "pause_nonactive", false);  // never pause a netplay session on focus loss: the DS link would drop
    // Minimal UI: touch overlay on, notifications quiet.
    if (!p.overlayPath.empty()) {
        kv(s, "input_overlay", p.overlayPath);
        kvb(s, "input_overlay_enable", true);
        kv(s, "input_overlay_opacity", "0.85");
    }
    kvb(s, "video_vsync", true);
    kvb(s, "video_fullscreen", true);
    kv(s, "menu_driver", "rgui");  // built-in font, needs no asset pack; the menu is hidden from users
    kvb(s, "menu_show_load_content_animation", false);
    kvb(s, "notification_show_config_override_load", false);
    kvb(s, "notification_show_autoconfig", false);
    kvb(s, "notification_show_refresh_rate", false);
    kvb(s, "rewind_enable", false);
    kvb(s, "run_ahead_enabled", false);  // incompatible with netplay
    return s;
}

std::string buildCoreOptions(const LaunchPlan& p) {
    std::string s = "# Generated by DSLink.\n";
    kv(s, "melonds_mac_address_mode", "from-username");  // MAC = f(netplay_nickname), see identity.cpp
    kv(s, "melonds_console_mode", p.dsi ? "dsi" : "ds");
    // With no cartridge (Download Play client) the core forces a native boot into the DS menu itself.
    kv(s, "melonds_boot_mode", p.role == Role::Client && p.contentPath.empty() ? "native" : "direct");
    // Two layouts, cycled by the overlay's "Schermi" button (R3): stacked (portrait) and side by side (landscape).
    kv(s, "melonds_number_of_screen_layouts", "2");
    kv(s, "melonds_screen_layout1", p.landscape ? "left-right" : "top-bottom");
    kv(s, "melonds_screen_layout2", p.landscape ? "top-bottom" : "left-right");
    kv(s, "melonds_show_cursor", "disabled");  // touch screen: no pointer cursor
    return s;
}

std::vector<std::string> buildCommandLine(const LaunchPlan& p, const std::string& appendConfigPath) {
    std::vector<std::string> a;
    if (!p.corePath.empty()) { a.push_back("-L"); a.push_back(p.corePath); }
    if (!appendConfigPath.empty()) { a.push_back("--appendconfig"); a.push_back(appendConfigPath); }
    if (p.role == Role::Host) a.push_back("-H");
    else { a.push_back("-C"); a.push_back(p.hostIp); }
    a.push_back("--port"); a.push_back(std::to_string(p.port));
    a.push_back("--nick"); a.push_back(p.identity.netplayNick());
    if (!p.contentPath.empty()) a.push_back(p.contentPath);
    return a;
}

std::string buildNetplayExtra(const LaunchPlan& p) {
    if (p.role == Role::Host) return "host;" + std::to_string(p.port) + ";" + p.identity.netplayNick();
    return "client;" + p.hostIp + ";" + std::to_string(p.port) + ";" + p.identity.netplayNick();
}

}  // namespace dslink
