package main

// Session modes (docs/DISTRIBUTED_MODE.md):
//   HOSTED       (default)  one device runs both emulators (radio = LOCAL Unix socket) and streams video/audio to the guest over WebRTC (stream = WEBRTC)
//   DISTRIBUTED             each device runs ONE runtime + melonDS; only the emulated DS radio crosses the LAN (radio = LAN, game stream = NONE:
//                           the local screen is shown by the device's own browser/app, nothing is streamed to the other device)
//   AUTO                    distributed first; hosted stays a manual fallback (no automatic probing yet - data first)

import (
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// LanSpec configures the LAN RadioTransport of one runtime.
type LanSpec struct {
	Role      string // "host" | "guest"
	Code      string // 6-digit room code (host: empty = generated by the runtime)
	URI       string // guest: dslink://join?c=..&s=..&h=ip:port (QR) - optional
	Impair    string // test only: delay=..,jitter=..,loss=..
	DiscAddr  string // guest: where discovery goes (default broadcast)
	DiscPort  int
	Advertise string // host: IP shown in the QR/URI
	Bind      string
	Mode      string // "distributed" | "auto" (what the user chose)
	Secret    string // 32 hex chars: session secret shared through the lobby (host: given to the runtime, guest: same value)
	HostAddr  string // guest: "ip:port" of the host runtime's LAN data port (from the lobby; skips discovery)
	GraceMs   int    // host: end the multiplayer session by itself this long after the last peer vanished
}

func sessionModeOf(r *Room) string {
	if r.Lan != nil {
		return "distributed"
	}
	return "hosted"
}

func slotStatuses(r *Room) []any {
	out := []any{r.Slots[0].Status()}
	for _, sl := range r.Slots[1:] {
		if sl != nil {
			out = append(out, sl.Status())
		}
	}
	return out
}

// lanSpecFromForm: nil = Hosted (the default and the already-verified path).
func lanSpecFromForm(r *http.Request) *LanSpec {
	mode := strings.ToLower(r.FormValue("mode"))
	if mode != "distributed" && mode != "auto" {
		return nil
	}
	role := strings.ToLower(r.FormValue("lan_role"))
	if role == "" {
		if r.FormValue("lan_code") != "" || r.FormValue("lan_uri") != "" {
			role = "guest"
		} else {
			role = "host"
		}
	}
	l := &LanSpec{Role: role, Code: strings.TrimSpace(r.FormValue("lan_code")), URI: r.FormValue("lan_uri"), Impair: r.FormValue("lan_impair"),
		DiscAddr: r.FormValue("lan_discovery_addr"), Advertise: r.FormValue("lan_advertise_ip"), Bind: r.FormValue("lan_bind"), Mode: mode}
	fmt.Sscanf(r.FormValue("lan_discovery_port"), "%d", &l.DiscPort)
	return l
}

func (l *LanSpec) runtimeArgs() []string {
	a := []string{"--session-mode", "distributed", "--radio-transport", "lan", "--stream-transport", "none", "--lan-role", l.Role, "--mp-timeout", "60000"}
	add := func(k, v string) {
		if v != "" {
			a = append(a, k, v)
		}
	}
	add("--lan-code", l.Code)
	add("--lan-secret", l.Secret)
	add("--lan-host", l.HostAddr)
	if l.GraceMs > 0 {
		a = append(a, "--mp-peer-grace-ms", fmt.Sprint(l.GraceMs))
	}
	add("--lan-uri", l.URI)
	add("--lan-impair", l.Impair)
	add("--lan-discovery-addr", l.DiscAddr)
	add("--lan-advertise-ip", l.Advertise)
	add("--lan-bind", l.Bind)
	if l.DiscPort > 0 {
		a = append(a, "--lan-discovery-port", fmt.Sprint(l.DiscPort))
	}
	return a
}

// createLanRoom starts this device's single runtime. The host needs a ROM; a guest has NO cartridge (DS Download Play).
func (s *Server) createLanRoom(w http.ResponseWriter, r *http.Request, dir string, lan *LanSpec) {
	rom1, title, sha := "", "DS Download Play", ""
	if lan.Role == "host" {
		rom1 = filepath.Join(dir, "player1.nds")
		if ok, err := s.saveUpload(r, "rom", rom1); !ok || err != nil {
			jsonOut(w, 400, map[string]string{"error": "manca il file .nds"})
			return
		}
		kv := parseKV(func() string { o, _ := run(s.env.RomCheck, rom1); return o }())
		if kv["status"] != "OK" {
			os.RemoveAll(dir)
			jsonOut(w, 422, map[string]string{"error": kv["message"]})
			return
		}
		title, sha = kv["title"], kv["sha256"]
	} else {
		if lan.Code == "" && lan.URI == "" {
			jsonOut(w, 400, map[string]string{"error": "serve il codice della partita"})
			return
		}
		// a guest normally has NO cartridge (DS Download Play); tests may give it one (homebrew radio test) with an optional upload
		if ok, _ := s.saveUpload(r, "rom", filepath.Join(dir, "player1.nds")); ok {
			rom1 = filepath.Join(dir, "player1.nds")
		}
	}
	room := &Room{Code: roomCode(), Title: title, SHA256: sha, Created: time.Now(), Solo: true, Lan: lan}
	if err := s.startSlots(room, rom1, ""); err != nil {
		for _, sl := range room.Slots {
			if sl != nil {
				sl.Stop()
			}
		}
		jsonOut(w, 500, map[string]string{"error": "impossibile avviare l'emulatore: " + err.Error()})
		return
	}
	room.newTokens()
	s.room = room
	out := map[string]any{"code": room.Code, "player": 1, "token": room.Tokens[0], "title": room.Title, "mode": "distributed", "lan_role": lan.Role}
	if lan.Role == "host" { // the runtime reports the room code + join URI in its status once the LAN socket is open
		for i := 0; i < 50; i++ {
			st := room.Slots[0].Status()
			if c, _ := st["lan_code"].(string); c != "" {
				out["lan_code"], out["lan_uri"] = c, st["lan_join_uri"]
				break
			}
			time.Sleep(100 * time.Millisecond)
		}
	}
	jsonOut(w, 200, out)
}
